### ISSUE TITLE
Extending the factory

### ISSUE THREAD

**Issue by ThisUsedToBeAnEmail** [tobyink/p5-zydeco#1]
Hi I'm wondering whether something like the following is possible. 

```
package Mxpress::PDF::Plugin::Mechanized;
use Zydeco factory_package => 'Mxpress::PDF';
class Plugin::Mechanized {
	extends Plugin::Image;
	factory mechanized (Object $file, Map %args) {
		$class->new(
			file => $file
			%args
		);
	}
	# ....
}
1;
```

my-script.pl

```
use Mxpress::PDF;
use Mxpress::PDF::Plugin::Mechanized;
```

**Comment by tobyink** [comment]
Wow, I only just looked at this now, but coincidentally it's along the lines of what I've been doing today.

The following test is currently passing:

```perl
use strict;
use warnings;
use Test::More;
use Test::Fatal;
 
package MyApp {
        use Zydeco;
        class Foo;
}
 
package MyApp {
        use Zydeco;
        class Bar {
                has foo (type => Foo);
        }
}
 
my $foo = MyApp->new_foo;
my $bar = MyApp->new_bar(foo => $foo);
 
isnt(
        exception { $bar->foo(undef) },
        undef,
);
 
done_testing;
```

So yeah, you should be able to load more classes as plugins.

**Comment by tobyink** [comment]
Also, I really want to have a hook that roles can do, like:

```perl
role Plugin {
  on_compose {
    ...;
  }
}
```

So the `on_compose` code gets called every time a class (or other role) consumes the Plugin role. It's not easy to do but should be possible.

So if all your plugins included `with Plugin`, then the main PDF class would be able to grab a list of plugins easily.

**Comment by ThisUsedToBeAnEmail** [comment]
Really, Sounds like a nice feature.

Crazy idea:
What I'd like is it to compile into a .pmc so that it is faster after the
first run. Having that will likely also help aid with OAPs using Zydeco
because they will know, for production they have sane pure perl code (or
even crazy fast xs.)

**Comment by ThisUsedToBeAnEmail** [comment]
Its just my opinion but new and shiny scare people. So making it
transparent might make it that little more awesome.

**Comment by tobyink** [comment]
You can kind of get that already with `use Zydeco debug => 1`. It will dump a big Data::Dumper hashref structure suitable for passing to MooX::Press.

You want:
```
BEGIN { $Data::Dumper::Deparse = 1 };
```

Dealing with closed-over lexical variables is left as an exercise for the reader.

**Comment by ThisUsedToBeAnEmail** [comment]
I just had this thought and now I understand the point.
