### ISSUE TITLE
More faster!

### ISSUE THREAD

**Issue by iamalnewkirk** [tobyink/p5-zydeco#2]
I like this a lot. I only wish that whatever it does at startup was more dynamic so it could load faster for simple declarations.

**Comment by tobyink** [comment]
0.100 was already a massive speed up. Honestly, it was annoyingly slow before then. A lot of the remaining start up time is compiling regular expressions, which can't be easily avoided.

A lot of features like multimethods, role hooks, Moose-native-traits-like delegation aren't loaded until they're actually used, so are already as fast as possible.

Of course, if you have patches that speed things up without losing functionality, I'd certainly consider them for inclusion.

**Comment by tobyink** [comment]
Zydeco::Lite is faster.
